language: python
python:
    - "3.7"
install:
    - pip install -r requirements/build-requirements.txt
    - pip install -e .
script:
    - pytest --cov=myflaskapp
after_success:
    - coveralls
notifications:
    email:
        on_success: never
